kind: ConfigMap
metadata:
  name: {{ .Values.app.name }}-trigger-pipeline
apiVersion: v1
data:
  trigger-pipeline.yaml: |
    apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: {{ .Values.app.name }}-run-build
      labels:
        backstage.io/kubernetes-id: {{ .Values.app.name }}
    spec:
      params:
        - name: git-url
          value: {{ .Values.git.repo }}
        - name: git-branch
          value: {{ .Values.git.branch }}
        - name: output-image
          value: {{ include "image.url" . }}
        - name: maven-image
          value: registry.redhat.io/ubi9/openjdk-21
      pipelineRef:
        name: {{ .Values.app.name }}-pipeline
      serviceAccountName: pipeline
      timeout: 1h0m0s
      workspaces:
        - name: source
          volumeClaimTemplate:
            spec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 5Gi
        - emptyDir: {}
          name: maven-settings
{{- if eq .Values.image.registry "Quay" }}
        - name: docker-config
          secret:
            secretName: {{ .Values.app.name }}-registry-creds
{{- else }}
        - name: docker-config
          emptyDir: {}
{{- end }}