apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-collector
  labels:
    name: otel-collector
    app.kubernetes.io/part-of: monitoring
    app.openshift.io/runtime: opentelemetry
  annotations:
    app.openshift.io/connects-to: jaeger
spec:
  replicas: 1
  selector:
    matchLabels:
      name: otel-collector
  template:
    metadata:
      labels:
        name: otel-collector
    spec:
      containers:
        - image: otel/opentelemetry-collector-contrib:0.109.0
          name: otel-collector
          args:
            - "--config=/conf/otel-collector-config.yml"
          ports:
            - name: health-check
              containerPort: 13133
            - name: otlp-receiver
              containerPort: 4317
          volumeMounts:
            - name: otel-collector-config
              mountPath: /conf
          resources:
            limits:
              memory: 128Mi
            requests:
              memory: 32Mi
      volumes:
        - name: otel-collector-config
          configMap:
            name: otel-collector-config
